spring:
  data:
    rest:
      base-path: /api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ecommerceapp
    password: ecommerceapp
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
